server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: sensor-service
          uri: lb://SENSOR-SERVICE
          predicates:
            - Path=/api/sensor/**
          filters:
            - AuthenticationFilter
            - RewritePath=/api/sensor/(?<segment>.*), /$\{segment}

        - id: alarm-service
          uri: lb://ALARM-SERVICE
          predicates:
            - Path=/api/alarm/**
          filters:
            - AuthenticationFilter
            - RewritePath=/api/alarm/(?<segment>.*), /$\{segment}

jwt:
  secret: your_jwt_secret_key_should_be_very_long_and_secure_at_least_256_bits

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka